### ISSUE TITLE
Can I ditch postman now?

### ISSUE THREAD

**Issue by kuator** [NTBBloodbath/rest.nvim#1]
Can I ditch postman now?

**Comment by NTBBloodbath** [comment]
`rest.nvim` should already be usable for daily use now, however there are things that can be done in postman but not in Neovim (for example, rendering images) _although I think it isn't something very useful_.

If you find that something essential is missing, feel free to open an issue or do a PR :slightly_smiling_face:

**Comment by kuator** [comment]
Pog!
