### ISSUE TITLE
parsing newlines

### ISSUE THREAD

**Issue by rudotriton** [NTBBloodbath/rest.nvim#10]
Hey, I'm running into some issues with newlines. For example when the response looks something like this:

```
{
    "a": "\n"
}
```

then I believe jq breaks somewhere along the way, since I get `parse error: Invalid string: control characters from U+0000 through U+001F must be escaped at line 2, column 1`.

Otherwise a really neat project 😉

**Comment by NTBBloodbath** [comment]
It seems that it's because the `echo` command has backslash escapes enabled (although in the man pages it says that it isn't the default behavior :confused:). I should have already solved it in a PR, when you can test it let me know if everything is going well :)

**Comment by NTBBloodbath** [comment]
It seems that it's because the `echo` command has backslash escapes enabled (although in the man pages it says that it isn't the default behavior :confused:). I should have already solved it in a PR, when you can test it let me know if everything is going well :)
