### ISSUE TITLE
Can't do post request (missing key/value pair in message header)

### ISSUE THREAD

**Issue by tin-pham** [NTBBloodbath/rest.nvim#108]
It used to work

It post the empty object so it response error with missing information
![image](https://user-images.githubusercontent.com/20679090/162351910-6550cf99-23b0-4d65-bc84-4c287e29b9ce.png)

I saw this in the bottom, it too long I can't see the full detail of it
![image](https://user-images.githubusercontent.com/20679090/162352001-7f7906fe-5769-42fa-abd3-7e4bbc20ff18.png)

Postman work just fine
![image](https://user-images.githubusercontent.com/20679090/162352036-796859b5-4be7-49de-baaa-2bdf96759f21.png)

**Comment by Gee19** [comment]
The error message mentions `request/init.lua:106`

```
    -- message header and message body are seperated by CRLF (see RFC 2616)
    -- for our purpose also the next request line will stop the header search
    if is_request_line(line_content) or line_content == "" then
      body_start = line_number
      break
    end
    if not line_content:find(":") then
      log.warn("Missing Key/Value pair in message header. Ignoring line: ", line_content)
      goto continue
    end
```
Try separating the headers / body with a newline.

**Comment by tin-pham** [comment]
Thanks, i seperate the header and body and now it work, great plugin
