### ISSUE TITLE
problematic single quotes

### ISSUE THREAD

**Issue by rudotriton** [NTBBloodbath/rest.nvim#12]
I came across another thing. Something like this: a single single-quote

```json
{
  "contents": "'\n"
}
```

throws `zsh:1: unmatched "`

When there is an equal number of single quotes they just get removed in the result window. Doesn't seem to happen with double quotes or backticks.

**Comment by NTBBloodbath** [comment]
Hey, it's expected because of how jq is handled in [Line 263](https://github.com/NTBBloodbath/rest.nvim/blob/main/lua/rest-nvim/init.lua#L263), basically the request body is passed to jq as that and if you pass a single quote it'll break the string.

```sh
# Good result
echo '{"contents": "foo"}' | jq .

# You have breaked the string, will raise an error
echo '{"contents": "'foo"}' | jq .
```

Don't know if I can find a workaround for it.

**Comment by rudotriton** [comment]
For future reference, I found that single quotes can be escaped when they are wrapped in a pair of single quotes.

```
echo '{"contents": "'\''foo"}' | jq .
```
