### ISSUE TITLE
Cannot use nested JSON objects

### ISSUE THREAD

**Issue by fishioon** [NTBBloodbath/rest.nvim#15]
E5108: Error executing lua Vim:E474: Trailing comma: }

```
POST https://reqres.in/api/users

Content-Type: application/json

{
    "name": "morpheus",
    "job": "leader",
    "hello": {}
}
```

**Comment by NTBBloodbath** [comment]
Hey, I already fixed the error locally. However, it seems that the plenary curl wrapper doesn't support the use of nested tables so there would still be a problem executing that request.

I'll see what I can do. Thanks for reporting it :slightly_smiling_face:

**Comment by fishioon** [comment]
Thank you. Look forward to good news

**Comment by NTBBloodbath** [comment]
I think the plenary curl wrapper needs some modifications to work with more complex use cases and was thinking if I could make those modifications to it myself. However, I'll be a bit busy these next two weeks so I don't think I'm making much progress.

I'll let you know as I make some progress with that. :)

**Comment by NTBBloodbath** [comment]
Hey, I've some good news!

There was a PR with a fix for plenary's curl wrapper, you can see it [here](https://github.com/nvim-lua/plenary.nvim/pull/167) and it seems to fixed this issue.

Lemme know if the issue persists for you so I'll remain this issue opened until I find a solution _in case it's still causing problems_.

![Screenshot_20210618_142634](https://user-images.githubusercontent.com/36456999/122603405-40e37700-d042-11eb-86c8-45c46d0b8ceb.png)

**Comment by NTBBloodbath** [comment]
The issue was already fixed a month ago by a PR in plenary's repository. Feel free to re-open this if you're still facing the issue.
