### ISSUE TITLE
Got error when trying to make request to subdomain of 5th level

### ISSUE THREAD

**Issue by osenvosem** [NTBBloodbath/rest.nvim#17]
Trying to make request to a domain with number of subdomains like `https://api.bitbucket.aa.bb.ru` but getting the following error:

```
E5108: Error executing lua ...rg/.config/nvim/plugged/rest.nvim/lua/rest-nvim/init.lua:251: Argument "start" is higher than "end"
```

**Comment by NTBBloodbath** [comment]
Hey, are you sure you entered the URL correctly and that the server is working fine?

I only get that error when my servers are still starting or are off.

**Comment by osenvosem** [comment]
> Hey, are you sure you entered the URL correctly and that the server is working fine?
> 
> I only get that error when my servers are still starting or are off.

I’m not, actually. Very may be that it wasn’t working correctly. If that’s the case it would be nice to have more informative error message. I’ll close the issue. Thanks for your work.

**Comment by NTBBloodbath** [comment]
> Very may be that it wasn’t working correctly. If that’s the case it would be nice to have more informative error message.

Yes, I was thinking of giving it a handle to be able to send a better error message. Thanks a lot for the suggestion!

**Comment by NTBBloodbath** [comment]
> Very may be that it wasn’t working correctly. If that’s the case it would be nice to have more informative error message.

Yes, I was thinking of giving it a handle to be able to send a better error message. Thanks a lot for the suggestion!
