### ISSUE TITLE
Does not work on Windows

### ISSUE THREAD

**Issue by mr-majkel** [NTBBloodbath/rest.nvim#19]
Hi, I have tried to run the plugin from under the Git bash for Windows (curl is available there). When run even with the simplest test example:

```http
POST https://reqres.in/api/users

Content-Type: application/json
{
  "name": "morpheus",
  "job": "leader"
}
```

 I am getting these errors:
```
E5108: Error executing lua [string ":lua"]:1: [rest.nvim] Failed to perform the request.
Make sure that you have entered the proper URL and the server is running.
Error executing luv callback:
...ata\Local\nvim\plugged\plenary.nvim\lua\plenary\path.lua:571: ENOENT: no such file or directory: /tmp/plenary_curl_cb9c41a5.headers
```

I think the first one is thrown because the response is empty, and it's empty because plenary fails to create (or read) from the file it creates when running curl (see here: https://github.com/nvim-lua/plenary.nvim/blob/master/lua/plenary/curl.lua#L63). Should I file an issue against plenary?

**Comment by NTBBloodbath** [comment]
Hey, I think you should. Although I don't know if they have in mind to support Windows :slightly_frowning_face:

**Comment by mr-majkel** [comment]
And here is [the issue](https://github.com/nvim-lua/plenary.nvim/issues/176) for plenary.

**Comment by NTBBloodbath** [comment]
Hey, I'm working right now on a PR for adding Windows support in plenary's cURL wrapper. I hope it'll be finished _and merged_ soon.

**Comment by mr-majkel** [comment]
@NTBBloodbath I have just tested the patch - it works for me:). I'll comment on the plenary PR itself, too

**Comment by NTBBloodbath** [comment]
Hey, I'm gonna close this 'cause the Windows patch was recently merged.

Regards :)
