### ISSUE TITLE
JSON syntax highlighting

### ISSUE THREAD

**Issue by disrupted** [NTBBloodbath/rest.nvim#2]
Great new plugin!

I was wondering if it would be possible to have proper syntax highlighting for the JSON responses, possibly also the request body? 

I am not really familiar with Vim's regex-based syntax highlighting, I've just had a quick look, but it seems to be highlighting everything in one color at the moment.

Perhaps we could even look into treesitter if that's an option (one can dream).

**Comment by NTBBloodbath** [comment]
Hi, I'm aware of this bug, I have already corrected it. I'll upload the fix soon!

Regarding the tree-sitter, if I'm not mistaken (I don't know how it works that thoroughly) a parser would have to be created so I don't think it's possible :(

**Comment by disrupted** [comment]
thank you, looks great!
