### ISSUE TITLE
Feature request: preview the API request

### ISSUE THREAD

**Issue by mr-majkel** [NTBBloodbath/rest.nvim#20]
Hi, me again:). It would be nice to be able to see what curl command has been run - either by default, or with some option to run(), like 'verbose=True' (it can also be some formatted opts table passed to curl). It will help to make sure that the headers and data were parsed correctly. I have spent some time figuring out why the headers were not picked up correctly (because of a # comment line, that seem not to be accepted), but I couldn't figure out what is the request structure.

Btw. is there any accepted way of commenting the http file?

**Comment by NTBBloodbath** [comment]
Hey, I've been working on this for a few minutes.

I've been thinking of making an optional argument to the run function, but the verbose mode of the curl wrapper is a DRY run. That is, it will return the arguments passed to curl without executing the request.

That said, if the `run(verbose)` function receives `true` as the argument, it will not execute the request, instead it will send a message to Neovim with the curl command that would be executed instead. Is that behavior okay for you?

I plan to make this possible so we can give a better debugging _or so I hope_ to #18

---

> Btw. is there any accepted way of commenting the http file?

Yeah, http files uses `#` for comments and rest.nvim is supposed to ignore them _although currently only the commented headers are ignored, I will open another issue to keep a track of it_
