### ISSUE TITLE
Feature request: add option to put header values in the .env

### ISSUE THREAD

**Issue by mr-majkel** [NTBBloodbath/rest.nvim#25]
Hi @NTBBloodbath, following the resolution of the token authorization, I was wondering if it is possible to have values of the headers defined in the .env file, and resolve them when parsing the http file. It works today for URL component, but not for headers. It comes useful especially with the tokens - you can put the token in .env file and then have all the calls re-use it. What do you think?

**Comment by NTBBloodbath** [comment]
I think it's a great idea, especially for security purposes related to the http file and follows DRY principles which is also a really good thing so you don't have to re-type the data.

It's not possible yet, but I think the implementation can be really fast on my side. Thank you for this request, I'm pretty sure that it'll be a really neat and useful feature!

**Comment by NTBBloodbath** [comment]
It's done, make sure to update rest.nvim :)

If you have other feature request or found a bug don't hesitate to open a new issue for them. Thank you so much for your requests and bugs reports, that helps a lot for the plugin to mature and be usable in a much wider range :heart:

**Comment by mr-majkel** [comment]
Hi @NTBBloodbath, I have updated rest.nvim, but it seems that sth is wrong. Now the headers are not coming through after the first resolved header value. Check this code:

```http
POST {{url}}

Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "morpheus",
  "job": "leader"
}
```

and this one:

```http
POST {{url}}

Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "morpheus",
  "job": "leader"
}
```
It seems that resolution of the variable stops parsing other lines. So if you have an expample like that:

```http
POST {{url}}

Content-Type: application/json
Authorization: Bearer {{token}}
Fancy-Header: {{some_variable}}

{
  "name": "morpheus",
  "job": "leader"
}
```
Only the Content-Type and Authorization is passed through in this case.
