### ISSUE TITLE
Commented headers go through to the call

### ISSUE THREAD

**Issue by mr-majkel** [NTBBloodbath/rest.nvim#29]
Hi, it seems that the comment line is ignored if **does not** have colon inside - this means that commenting out headers stopped working. I guess it is about order of parsing actions. The line should be ignored completely if it starts with #.

**Comment by NTBBloodbath** [comment]
Hey, it can take a bit of time because Lua pattern matching is not the same as the regex in other languages but I'll try to fix it ASAP!
