### ISSUE TITLE
[Feature Request] Import body from file

### ISSUE THREAD

**Issue by jens1205** [NTBBloodbath/rest.nvim#31]
It would be nice if the body of the request could be imported from another file.

E.g.:
`POST http://localhost:8100/v1/orders
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
X-Idempotency-Key: aaaaa

< ./order.json

###
`

**Comment by jens1205** [comment]
See MR #32 for an implementation

**Comment by NTBBloodbath** [comment]
Hey sorry for the late reply. Already merged it, thank you so much :slightly_smiling_face:
