### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by NTBBloodbath** [NTBBloodbath/rest.nvim#36]
Hey, as you can see `rest.nivm` is growing and maturing by a lot, and that's pretty awesome!

But I can't be here all the time to manage issues and PRs and that's not a big deal :(

That's why I opened this issue, we're looking for maintainers to handle these things too!

I'll maybe not reply today since I'll not be at home but I'll be glad to reply when I come back :)

Regards!

**Comment by jens1205** [comment]
Hi @NTBBloodbath ! I could help (although I will be on vacation soon...)

**Comment by NTBBloodbath** [comment]
Nice, thank you!

I'll send you the invitation ASAP, feel free to merge your PRs too. Loving your changes :)

**Comment by jens1205** [comment]
I just merged my PRs. I hope they are all sane. Will be on vacation from tomorrow on (for one week)

**Comment by NTBBloodbath** [comment]
I'll close it for now, let's re-open it if we need more maintainers. Thank you!
