### ISSUE TITLE
URLEncode

### ISSUE THREAD

**Issue by hjanuschka** [NTBBloodbath/rest.nvim#4]
hello 🤚 ,

when using "?q=[1,2,3]" - it fails to load.
i expect that, `[1,2,3]`  needs to be encoded into `q=%5B1%2C2%2C3%5D`  before being sent.

i love this project ❤️  its like postman in vim - vimMan!

**Comment by hjanuschka** [comment]
sample 

`1.http`:
```
GET https://reqres.in/api/users/2?a=[1,2,3]
```

<img width="2523" alt="Bildschirmfoto 2021-05-07 um 15 40 16" src="https://user-images.githubusercontent.com/2891702/117458452-9bb98700-af4a-11eb-9a4c-a28a836f3529.png">

**Comment by hjanuschka** [comment]
using `QUERIES{}`  works, but would be nice to support the above thing too

**Comment by tomaskallup** [comment]
Hey, I'm running into the same issue as above, I need to send a request with space in query and nothing I tried worked.
example: `/suggestion?query=U mestanskeho`
I have tried:
 - `/suggestion?query=U+mestanskeho`
 - `/suggestion?query=U%20mestanskeho`
 - `/suggestion?query="U mestanskeho"`
Is this somehow being worked on or is there a specific format I need?

**Comment by rti** [comment]
+1 for spaces in urls :)
