### ISSUE TITLE
Selene lint action broken

### ISSUE THREAD

**Issue by jens1205** [NTBBloodbath/rest.nvim#42]
Selene always complains about an unknown goto
```
error[parse_error]: unexpected token `goto`
    ┌─ lua/rest-nvim/init.lua:183:4
    │
183 │             goto continue
    │             ^^^^ expected 'end'

```
This is a known issue (https://github.com/Kampfkarren/selene/issues/224)

**Comment by NTBBloodbath** [comment]
Hey, thank you for pointing it to me jens!

I'll take a look at the workaround to fix it asap, we don't want false linting errors.

**Comment by jens1205** [comment]
Some interesting background: neovim officially only supports lua 5.1. But the "goto" keyword has been introduced with lua 5.2.

So why does our code work? Neovim ships with luajit 2.1.0 which includes some extensions from lua 5.2 https://luajit.org/extensions.html

But for this ticket it is questionable if our linter should really accept the full feature set of lua 5.2.

Perhaps the best way to fix is to rewrite the one function not to use goto

**Comment by jens1205** [comment]
Or we switch from selene to luacheck https://github.com/mpeterv/luacheck/ Maybe they support the features of luajit:

> Luacheck supports checking Lua files using syntax of Lua 5.1, Lua 5.2, Lua 5.3 and LuaJIT. 

And luacheck is also proposed in a new template for nvim plugins: https://github.com/nvim-lua/nvim-lua-plugin-template

**Comment by NTBBloodbath** [comment]
I didn't really understood how to fix that selene issue because I already selected `lua52` as our stdlib because of what you've said before and was the same result.

Let's take a look at luacheck, hope it has a github action so we can setup it very quickly. If not then there's no problem, we can do it from scratch :)

**Comment by NTBBloodbath** [comment]
I think it's done. Already changed our linter to luacheck and squashed some errors that luacheck detected :)
