### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by Chaitanyabsprip** [NTBBloodbath/rest.nvim#43]
I can't get this plugin to work.  
I use packer with the latest neovim stable release.
I am neither getting the syntax highlight nor the keymaps to commands are doing anything

**Comment by jens1205** [comment]
I had also trouble using the `<Plug>RestNvim` mapping.

Can you try using something like 
`vim.api.nvim_set_keymap('n', '<Leader>e', [[<cmd>lua require'rest-nvim'.run()<cr>]], {noremap = true, silent = true})` ?

**Comment by Chaitanyabsprip** [comment]
I tried this, it is sort of working, in the sense that I am at least getting an error now. 
`packer.nvim: Error running config for rest.nvim: [string "..."]:0: attempt to index upvalue '' (a nil value)`

**Comment by jens1205** [comment]
Could you please post the important parts of your init.lua?

**Comment by Chaitanyabsprip** [comment]
```lua
local u = require "utils"
local ntst = {noremap = true, silent = true}
------------
  use {
    'NTBBloodbath/rest.nvim',
    config = function()
      require('rest-nvim').setup()
      u.keymap("n", "<leader>rn", "<cmd>lua require('rest-nvim').run()<CR>",
               ntst)
    end
  }

```
This is how I am installing the plugin

```lua
require("settings")
require("mappings")
require("plugins")
vim.cmd [[source /home/chaitanya/.config/nvim/vimscripts/ginit.vim]]

-- plugins configurations

require("plugin-config.nvim-autopairs")
require("plugin-config.telescope")
-- require("plugin-config.themes.indent-line")
require("plugin-config.toggleterm")
require("plugin-config.lsp-fastaction")
require("plugin-config.nvim-compe")
require("plugin-config.nvim-tree")
require("plugin-config.nvim-treesitter")
require("plugin-config.startify")
require("plugin-config.themes")
require("plugin-config.themes.lualine")
require("plugin-config.trouble")

-- LSP
require("lsp.lsp-settings")

require("lsp.bash-ls")
require("lsp.clangd-ls")
require("lsp.css-ls")
require("lsp.dart-ls")
require("lsp.efm-general-ls")
require("lsp.emmet-ls")
require("lsp.gopls")
require("lsp.haskell-ls")
require("lsp.html-ls")
require("lsp.java-ls")
require("lsp.js-ts-ls")
require("lsp.json-ls")
require("lsp.lua-ls")
require("lsp.nvim-lsp")
require("lsp.pyright-ls")

vim.cmd [[source /home/chaitanya/.config/nvim/vimscripts/autocommands.vim]]
```
This is my init.lua

**Comment by jens1205** [comment]
Hi,

I guess you are missing plenary?

use { 'NTBBloodbath/rest.nvim',
 requires = { 'nvim-lua/plenary.nvim' }, config = function() require('rest-nvim').setup() end }

Regards
Jens

**Comment by Chaitanyabsprip** [comment]
I am not, I have it installed that is why I did not put that requirement

**Comment by NTBBloodbath** [comment]
I was facing a similar issue (the same upvalue error) with lspconfig yesterday. Can you please try defining `u` and `ntst` inside the config function? So it should look like

```lua
  use {
    'NTBBloodbath/rest.nvim',
    config = function()
	  local u = require "utils"
	  local ntst = {noremap = true, silent = true}
      require('rest-nvim').setup()
      u.keymap("n", "<leader>rn", "<cmd>lua require('rest-nvim').run()<CR>",
               ntst)
    end
  }
```

Hope it works!

**Comment by Chaitanyabsprip** [comment]
This makes it work, thanks!

**Comment by amiroslaw** [comment]
If you have keymap with <Plug> you shouldn't bind it with noremap option.
