### ISSUE TITLE
Allow unknown certificate

### ISSUE THREAD

**Issue by rafi** [NTBBloodbath/rest.nvim#46]
Is there a way to force `curl -k` to skip ssl verification?

**Comment by NTBBloodbath** [comment]
Hey, sorry for the late reply!

There should but I'm not really sure about how should we implement this because it will need some extra logic. Maybe adding a new option to our `run()` function? It makes sense for me but let me know if it's fine for you.

Regards

**Comment by rafi** [comment]
Hi, either a `run()` argument or a global `setup()` setting would be great @NTBBloodbath.

**Comment by NTBBloodbath** [comment]
Now that you mention it, I think a `setup()` setting could be a better approach because we will avoid having to create new mappings or modify the existing ones :thinking:

**Comment by rafi** [comment]
Yes, sounds like an easier solution than complicating `run()`.

**Comment by NTBBloodbath** [comment]
Great, I'll start implementing it today, shouldn't be hard tho
