### ISSUE TITLE
Crashes neovim sometimes

### ISSUE THREAD

**Issue by mhanberg** [NTBBloodbath/rest.nvim#48]
Hi!

Sometimes, when running `:lua require("rest-nvim").run()`, my entire neovim crashes and leaves my terminal in a funky state.

<img width="1913" alt="image" src="https://user-images.githubusercontent.com/5523984/129250275-64eb88fe-9970-4236-96d9-ea4e19974575.png">

I am not sure exactly what is happening here 😅

Dropbox link to the macOS crash report: https://www.dropbox.com/s/r9qe4kfg3skgcfj/nvim-crash-report.txt?dl=0
<details>
<summary>
neovim version
</summary>
<pre>
NVIM v0.5.0
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/Users/mitchellhanberg/.asdf/downloads/neovim/ref-stable/build/config -I/Users/mitchellhanberg/.asdf/downloads/neovim/ref-stable/src -I/Users/mitchellhanberg/.asdf/downloads/neovim/ref-stable/.deps/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include -I/usr/local/opt/gettext/include -I/Users/mitchellhanberg/.asdf/downloads/neovim/ref-stable/build/src/nvim/auto -I/Users/mitchellhanberg/.asdf/downloads/neovim/ref-stable/build/include
Compiled by mitchellhanberg@MitchellHanberg.attlocal.net

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
</pre>
</details>

**Comment by NTBBloodbath** [comment]
Hey, I'm sorry for the late reply!

This is really, really weird. Are you sure that `rest.nvim` is the culprit? I don't really know how can we debug this if that's the case :confused:

**Comment by jens1205** [comment]
I am using rest.nvim on Linux and on Mac and had not encountered these problems so far.

Regards
Jens

**Comment by mhanberg** [comment]
I agree that this is very weird. 

I am wondering if it could be related to Plenary.Job, since the crash report states something about libuv (I think).

**Comment by jens1205** [comment]
does this still happen, or can this issue be closed? BTW, the dropbox-link in https://github.com/NTBBloodbath/rest.nvim/issues/48#issue-969354059 is gone...

**Comment by teto** [comment]
if you find a way to reproduce this reliably on neovim master, please report it to the neovim repo: it's a neovim bug, not this plugin's.
