### ISSUE TITLE
E488: trailing characters

### ISSUE THREAD

**Issue by yofriadi** [NTBBloodbath/rest.nvim#6]
using the example from readme give me the error above, what I'm missing?

```
GET http://localhost:3000/foo

HEADERS {
    "Content-Type": "application/json"
}
```

**Comment by yofriadi** [comment]
maybe example for each request method would be super helpful

**Comment by NTBBloodbath** [comment]
Hey, the README examples aren't functional, they were made to show the syntax. However, it would be nice to change them :)

For functional examples, you can see the [tests](https://github.com/NTBBloodbath/rest.nvim/tree/main/tests) directory.

**Comment by tosiek88** [comment]
Hi I have still this issue I am using basic_get.http, coursor is on GET word, color syntax is highlighted
