### ISSUE TITLE
Feature request: import system

### ISSUE THREAD

**Issue by timsofteng** [NTBBloodbath/rest.nvim#65]
Hello.
I want to create system for testing API. But it slightly anoying to past manually some data into each request file. E.g token
Is it possible to store variables in done file and just import it to request files?

**Comment by NTBBloodbath** [comment]
@timsofteng Hey, yeah it is possible by using .env files to declare environment variables.

So by example your .env file can look like this
sh
TOKEN=my_s3cre1_tk


And then you can use it in your http file, rest.nvim will automatically replace the variable by its value, you can see this like string interpolation.
http
Authentication: Bearer {{TOKEN}}


Regards

**Comment by timsofteng** [comment]
Awesome.
Thanks
