### ISSUE TITLE
[Feature request] Support mode for env variables.

### ISSUE THREAD

**Issue by AllenDang** [NTBBloodbath/rest.nvim#68]
Nice work! This is the restclient I'm looking for a long time.

Here is a common case when I test restful api in day to day work. 

Define a env named {{base_url}} in both `production` and `local` modes. So I could switch to `local` to test the code in local server, and switch to `prod` after deployment.

The {{base_url}} may looks like this.

In `production` mode, base_url is `http://xyz.abc/api/v1.0/something`, and in `local` mode base_url is `http://localhost:8080`.

If rest.nvim could support this, I could replace my rest client for good.

**Comment by NTBBloodbath** [comment]
Hey, thank you for kind words :)

This sounds like a really good feature, can you please tell me how do you switch modes? In that way I'll have a cleaner idea about how to implement this!

Regards

**Comment by AllenDang** [comment]
Here is a basic idea for your reference.

1. Define env variables like this.
```
[Production] <- this is the mode name
base_url = ...

[Local]
base_url = ...
```

2. Use base_url as usually in http file.

3. Provide a set of api to:
1. Get all the modes.
2. Get current activated mode's name.
3. Set current activated mode by name.

With those APIs I could integrate them easily with telescope (mode picker), feline (status line).

**Comment by NTBBloodbath** [comment]
Thank you so much for such detailed explanation!

Never saw something like this before, do you know if this format is valid in NodeJS dotenv package? I want to know if this already exists so I can take a look at some implementations haha, it seems that we will need to change how our `.env` files reading process works

**Comment by NTBBloodbath** [comment]
Alright so I'm implementing this on my own way atm, do you have any idea about how should we identify what environment mode should be used?

**Comment by jens1205** [comment]
Perhaps you can draw some inspiration from https://www.jetbrains.com/help/idea/exploring-http-syntax.html#example-working-with-environment-files

**Comment by AllenDang** [comment]
@NTBBloodbath Always use the first mode defined in env file as default is good enough for me.

**Comment by cagucor** [comment]
@NTBBloodbath  what is the status of this feature? 
I would love to have something like this, I'll learn lua if it helps to get it done faster 😀
