### ISSUE TITLE
Failed to execute the run method

### ISSUE THREAD

**Issue by captainko** [NTBBloodbath/rest.nvim#69]
Thank you for making this amazing plugin. 

I'm getting this error while testing with [`basic_get.http`](https://github.com/NTBBloodbath/rest.nvim/blob/de5cb9e76f278e002a3a7f1818bdb74d162b9d69/tests/basic_get.http)
![image](https://user-images.githubusercontent.com/32269291/134162628-1c058ca6-c643-4c84-93f2-45de4e575750.png)

Here is my config
```lua
  use {
    "NTBBloodbath/rest.nvim",
    requires = { "nvim-lua/plenary.nvim" },
    config = function()
      local nnoremap = cko.nnoremap
     
      nnoremap { "<LocalLeader>rx", "<Cmd>lua require('nvim-rest').run()<CR>" } 
      require("rest-nvim").setup {
        -- Open request results in a horizontal split
        result_split_horizontal = false,
        -- Skip SSL verification, useful for unknown certificates
        skip_ssl_verification = true,
        -- Highlight request on run
        highlight = { enabled = true, timeout = 150 },
        -- Jump to request line on run
        jump_to_request = false,
      }
    end,
  }

```

**Comment by NTBBloodbath** [comment]
Hey buddy I'm so sorry for the late reply, my net died yesterday.

Can you please share information about your system? e.g. if you're running on WSL. This is probably a plenary bug so I can't directly fix this on my side :confused:

**Comment by lamtuanvu** [comment]
Hi @NTBBloodbath,

I faced with the same problem. I'm running on MacOS Bigsur 11.5.2 and I observed that the problem does not happen with plenary.nvim@06266e7bf675ba9af887fb6d1661b289fdd9bcf4 . Something changes that cause the problem after that commit.

Thanks,

**Comment by marcomayer** [comment]
Got the same issue on MacOs 10.15.7

**Comment by NTBBloodbath** [comment]
Hmm maybe we should move this to plenary's repo? I would love to help debugging this but it seems that it's not a direct issue from rest.nvim so I can't really fix this by myself because it works just fine in Linux and I don't have a Mac :confused:

**Comment by jens1205** [comment]
I have a Mac from work and could try to tackle this problem. But that might take some days as I am quite busy....

**Comment by captainko** [comment]
I think it's not related to OS. I still have this issue on Ubuntu.

**Comment by captainko** [comment]
@NTBBloodbath  have you tested this plugin with the latest neovim (0.6) yet?

**Comment by NTBBloodbath** [comment]
> @NTBBloodbath have you tested this plugin with the latest neovim (0.6) yet?

Hmm I think so, yeah. We have a neovim-nightly repository on Fedora and I updated Neovim yesterday. This is my build version if it's useful

`NVIM v0.6.0-dev+331-gaba397991`

**Comment by jens1205** [comment]
hmm, for me its also working with the following version on Mac:

`NVIM v0.6.0-dev+1657-ga373ca1d8`

**Comment by jens1205** [comment]
Interesting thing is that @lamtuanvu mentions in https://github.com/NTBBloodbath/rest.nvim/issues/69#issuecomment-925464888 that it works with plenary.nvim@06266e7bf675ba9af887fb6d1661b289fdd9bcf4. But if I compare master to this commit, nothing in plenary curl or plenary path has changed...

**Comment by jens1205** [comment]
Perhaps those that encounter the problem could do the following:
1. make sure that you are allowed to create files in /tmp (although it would be very strange if this is not the case)
2. have a look in /tmp if there are plenary files lying in /tmp (if I'm right the error is triggered by a readline on the filename, the unlink happens of course later...
3. while using rest.nvim, watch the /tmp directory (e.g. with `while true; do ls /tmp | grep plenary 2> /dev/null; done`) to see if a plenary file is created in /tmp and if the filename differs.

**Comment by captainko** [comment]
@jens1205  Thank you for such a detailed instruction. I have run the "watch" command but don't see any header files getting created by `plenary`. The `curl ...` command does create a header file.

I gonna close the issue here because I think it's plenary's bug.

**Comment by jonathan-raines** [comment]
Don't mean to kick a dead horse, but I'm also running into this issue. I observed that running the latest nvim.appimage on Ubuntu does work. Running the latest 0.5 release or the latest 0.6 release, both built from source, does not work.

Hope this info helps
