### ISSUE TITLE
Command/binding to copy request as curl

### ISSUE THREAD

**Issue by caenrique** [NTBBloodbath/rest.nvim#71]
Would be nice to share with other people as a curl command, and not just printing it for inspection.
I noticed that the curl command is including some headers from plenary. Would it be posible to keep this to the simplest for this functionality? 
Thanks! :)

**Comment by NTBBloodbath** [comment]
Hi, this sounds really cool and useful. I'll be glad to work on it!

About the plenary stuff, it seems that plenary writes all the needed data to a temp file in order to minify the cURL command and don't fill it with a ton of arguments afaik so maybe we can make rest.nvim read the temporal file and return the cURL command with all the data :thinking:

**Comment by jens1205** [comment]
hmm, the temp file is only used for the response headers, not the request headers:

```       
    -D, --dump-header <filename>
              (HTTP FTP) Write the received protocol headers to the specified file.

              This option is handy to use when you want to store the headers that an HTTP site sends to you. Cookies from the headers could then be read in a second curl invocation by using the -b, --cookie option! The -c, --cookie-jar option is a better way to store cookies.

              When used in FTP, the FTP server response lines are considered being "headers" and thus are saved there.

              If this option is used several times, the last one will be used.

              See also -o, --output.
```

The headers of the request you can see in the dry-run are cut of, but if you use `:messages` you can see everything:
```
[rest.nvim] curl -sSL -D /tmp/plenary_curl_633943fc.headers --compressed -X POST -H Some-Other-Header:  very-important -H Content-Type:  application/json --data-raw {    "name": "morpheus",    "job": "leader",    
"array": ["a", "b", "c"],    "object_ugly_closing": {      "some_key": "some_value"}} https://reqres.in/api/users    
```

So I don't think anything is missing?

**Comment by caenrique** [comment]
cool, so we could remove the `-D /tmp/plenary_curl_633943fc.headers` part for this when copying it to clipboard, and it will be the same except it won't write the response headers to a file, right?
