### ISSUE TITLE
Treesitter parser reinstalled

### ISSUE THREAD

**Issue by gegoune** [NTBBloodbath/rest.nvim#75]
Hi there,

every time `:TSUpdate` gets executed html parser (set up as per README) gets reinstalled even though there probably were no updates. Do you think this can be fixed somehow? Or perhaps should this parser be added to `nvim-treesitter/nvim-treesitter` which would simplify installation process for this plugin as well?

**Comment by gegoune** [comment]
@NTBBloodbath I have never done that (PR re treesitter) but could give it a go if you don't mind me submitting your code.

**Comment by NTBBloodbath** [comment]
Hi, sure thing buddy. Feel free to do it :)

**Comment by gegoune** [comment]
Awesome! Not sure if I did it right: https://github.com/nvim-treesitter/nvim-treesitter/pull/1978

Can send you README changes for rest.nvim as well (do you mind if I apply linter's suggestions for it?). Also, should `after/queries/http/highlights.scm` be removed from this repo?

**Comment by NTBBloodbath** [comment]
Hi, yeah you did it well. Thanks per doing this!

I added a notice in our README telling that our tree-sitter parser now requires json one to be installed. Let's wait until your PR is merged so we can finally change the tree-sitter parser installation steps and simplify stuff :)

> do you mind if I apply linter's suggestions for it?

Go for it, I feel like it's worth :p

> Also, should `after/queries/http/highlights.scm` be removed from this repo?

Hmm I'm not really sure tbh. Let's wait and see if it's really needed here so we can safely remove it later.
