### ISSUE TITLE
Request headers values with colon symbol

### ISSUE THREAD

**Issue by frei-0xff** [NTBBloodbath/rest.nvim#76]
Request headers fields containing colon symbol in their value aren't send properly, for example
with request
`POST https://api.host.com/v1/login
Origin: https://account.host.com
Content-Type: application/json

{ "user": "user", "password": "pass" }`
on the server side I'm getting "https" instead of "https://account.host.com" in Origin field.

**Comment by NTBBloodbath** [comment]
Hi, thank you so much per reporting _and fixing_ this!

Closing this issue because your PR with the fix have been merged :)

Regards
