### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by yofriadi** [NTBBloodbath/rest.nvim#97]
![Screen Shot 2022-01-23 at 10 12 10](https://user-images.githubusercontent.com/24536844/150663479-d022a363-8ec4-4d72-857a-829c37b8d22f.png)

using example request but throw error
neovim v0.6.1
curl 7.77.0

**Comment by phenrique** [comment]
I'm having the same problem

**Comment by aimran-adroll** [comment]
Same issue. 
This was is a doozy. Strangely enough for me, its transient. A certain iteration of `PackerCompile + PackerInstall` fixes it. But almost always the next call to `run` breaks it again

**Comment by NTBBloodbath** [comment]
Hey, my apologies for the very late response!

This issue looks very weird to me. I'll check first from our side to discard issues in rest.nvim code before taking actions in plenary and start debugging it.

Thanks for providing error tracebacks btw, now I know where should I start debugging from both our side and plenary side.

I'll start debugging tonight once I'm done with work.

Cheers

**Comment by aimran-adroll** [comment]
Thanks for looking into it @NTBBloodbath. Super helpful plugin

Let me us know if you need more details

**Comment by Ezechi3l** [comment]
I had the same issue and after checking the code it was coming from plenary. 

The [issue](https://github.com/nvim-lua/plenary.nvim/issues/269) is now [resolved](https://github.com/nvim-lua/plenary.nvim/pull/334) so you just have to update it.
